### ISSUE TITLE
Sketch Toolbox integration

### ISSUE THREAD

**Issue by onordbo** [RayPS/my-sketch-colors#5]
Would love to see this added to the Sketch Toolbox database for even simpler installation. Mostly for those of use that aren't that familiar with the command line (on any level).

I don't even know if it's possible, but it should be. Right?

Here's the link:
http://sketchtoolbox.com

**Comment by RayPS** [comment]
I think this is not possible, because it's not a plugin and very different to others in SketchToolbox.
Besides this is dangerous, users will just click on the install button and they will never see the Readme on Github page, their colors will be replaced.
The command line is not familiar but it's really easy to done.
